Repository GWC-UNCC/Girls-Who-Code-at-UNCC, pull requests merged in 2022-09, with the labels that each got.

#230 Bug/cms uploaded images
  .gitattributes
  content/about/_index.md
  static/admin/config.yml
Labels: bug, about

#231 Only display partner events via hosts front matter
  content/portfolio/gwc-website-project-2022.md
  content/portfolio/venture-team-building.md
  layouts/partials/partnership.html
  static/admin/config.yml
Labels: enhancement, about

#235 Feat/display hosts
  layouts/partials/partnership.html
  layouts/portfolio/single.html
Labels: enhancement, style, about, portfolio

#236 FAQ: left align, and fix spacing
  layouts/partials/faqs.html
Labels: bug, about

#240 Update Portfolio Posts “website-launch-party”
  content/portfolio/website-launch-party.md
  static/images/launchpartyrecap.jpeg
Labels: netlify-cms/draft

#241 Update Portfolio Posts “axe-hacks-2022”
  content/portfolio/axe-hacks-2022.md
  static/images/axehacksrecap.jpeg
Labels: netlify-cms/pending_publish

#242 Update Portfolio Posts “axe-hacks-2022”
  content/portfolio/axe-hacks-2022.md
  static/images/projectwinners.jpeg
Labels: netlify-cms/pending_publish

#243 Update Portfolio Posts “internship-panel”
  content/portfolio/internship-panel.md
  static/images/internshippanelrecap.jpeg
Labels: netlify-cms/pending_publish

#245 Update Portfolio Posts “eoy-celebration”
  content/portfolio/eoy-celebration.md
Labels: netlify-cms/pending_publish

#244 Update Portfolio Posts “venture-team-building”
  content/portfolio/venture-team-building.md
Labels: netlify-cms/pending_publish

#246 Update Portfolio Posts “axe-hacks-2022”
  content/portfolio/axe-hacks-2022.md
Labels: netlify-cms/draft

#249 Update Portfolio Posts “venture-team-building”
  content/portfolio/venture-team-building.md
Labels: netlify-cms/draft

#248 Update Portfolio Posts “internship-panel”
  content/portfolio/internship-panel.md
Labels: netlify-cms/draft

#247 Update Portfolio Posts “eoy-celebration”
  content/portfolio/eoy-celebration.md
Labels: netlify-cms/draft

#250 Update Portfolio Posts “gwc-website-project-2022”
  content/portfolio/gwc-website-project-2022.md
Labels: netlify-cms/draft

#251 Update Portfolio Posts “gwc-website-project-2022”
  content/portfolio/gwc-website-project-2022.md
Labels: netlify-cms/draft

#252 Create Portfolio Posts “create-a-tech-bracelet”
  content/portfolio/create-a-tech-bracelet.md
  static/images/you-1-.png
Labels: netlify-cms/pending_publish

#254 Create Portfolio Posts “code-lounge-1”
  content/portfolio/code-lounge-1.md
  static/images/code-lounge-0915-1-.png
Labels: netlify-cms/pending_publish

#253 Create Portfolio Posts “code-lounge”
  content/portfolio/code-lounge.md
  static/images/code-lounge-0915.png
Labels: netlify-cms/pending_publish

#255 Update Portfolio Posts “create-a-tech-bracelet”
  content/portfolio/create-a-tech-bracelet.md
Labels: netlify-cms/pending_publish

#256 Update Portfolio Posts “create-a-tech-bracelet”
  content/portfolio/create-a-tech-bracelet.md
Labels: netlify-cms/pending_publish

#257 Update Portfolio Posts “code-lounge-1”
  content/portfolio/code-lounge-1.md
Labels: netlify-cms/pending_publish

#258 Update Portfolio Posts “code-lounge”
  content/portfolio/code-lounge.md
Labels: netlify-cms/pending_publish

#259 Update Portfolio Posts “code-lounge”
  content/portfolio/code-lounge.md
Labels: netlify-cms/pending_publish

#260 Update Portfolio Posts “code-lounge-1”
  content/portfolio/code-lounge-1.md
Labels: netlify-cms/pending_publish

#261 Update Portfolio Posts “code-lounge”
  content/portfolio/code-lounge.md
Labels: netlify-cms/pending_publish

#262 Update Portfolio Posts “code-lounge-1”
  content/portfolio/code-lounge-1.md
Labels: netlify-cms/pending_publish

#263 Update Portfolio Posts “code-lounge-1”
  content/portfolio/code-lounge-1.md
Labels: netlify-cms/pending_publish

#264 Update Portfolio Posts “code-lounge-1”
  content/portfolio/code-lounge-1.md
Labels: netlify-cms/pending_publish

#265 Update Portfolio Posts “code-lounge-1”
  content/portfolio/code-lounge-1.md
Labels: netlify-cms/pending_publish

#232 adding schedule for re-deploys
  .github/workflows/cd.yml
Labels: enhancement

#268 Create Library Posts “gwc-merchandise-interest-form”
  content/library/gwc-merchandise-interest-form.md
  static/images/gwc-merchandise-form-thumbnail.png
  static/images/untitled-design-10-.png
Labels: netlify-cms/pending_publish
